### ISSUE TITLE
ember install ember-cli-swiper -> Unexpected token '(' at index.js:7

### ISSUE THREAD

**Issue by benjaminlong** [Suven/ember-cli-swiper#35] opened 2016-10-24 07:50 UTC
Hello everyone.

When installing your addon, I received this error:

```
$ ember install ember-cli-swiper
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Installed packages for tooling via npm.
/.../node_modules/ember-cli-swiper/index.js:7
  included(app) {
          ^
Unexpected token (
/.../node_modules/ember-cli-swiper/index.js:7
  included(app) {
          ^
SyntaxError: Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Addon.lookup (/.../node_modules/ember-cli/lib/models/addon.js:873:19)
    at /.../node_modules/ember-cli/lib/models/addons-factory.js:47:36
    at visit (/.../node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```

I'm currently using node v3.5.2 and ember v2.5 (Not sure it's related)
Regarding this issue, I made a simple modification. 

See here: https://github.com/benjaminlong/ember-cli-swiper/commit/7251b303e2578b82e49da7a09055863aee30d165

Let me know if you think a pull-request is needed.
All the best!
Love your addon so far.

**Comment by Suven** [comment] 2016-10-24 08:44
duplicate of #1

**Closed by Suven** 2016-10-24 08:44 UTC

**Comment by benjaminlong** [comment] 2016-10-24 08:52
My bad. Didn't see this issue.
