### ISSUE TITLE
Unexpected token error while installing the ad-on

### ISSUE THREAD

**Issue by sunil-shrestha** [Suven/ember-cli-swiper#34] opened 2016-10-22 14:07 UTC
I was trying to install this ad-on and came across this error(tested with Ember versions 2.9.0-beta.2  and 2.10.0-beta.2) .

```
$ ember install ember-cli-swiper
MyProject/node_modules/ember-cli-swiper/index.js:7
  included(app) {
          ^
Unexpected token (
MyProject/node_modules/ember-cli-swiper/index.js:7
  included(app) {
          ^
`SyntaxError:` Unexpected token (
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.Addon.lookup (MyProject/node_modules/ember-cli/lib/models/addon.js:998:19)
    at MyProjects/node_module/ember-cli/lib/models/addons-factory.js:48:38
    at visit (MyProject/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```

**Comment by Suven** [comment] 2016-10-24 06:58
duplicate of #1

**Closed by Suven** 2016-10-24 06:58 UTC
